# Generated by Django 4.0.6 on 2022-08-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indexgoodsbanner',
            table=None,
        ),
    ]
