# Generated by Django 4.0.6 on 2022-08-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_indexgoodsbanner_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='stock',
            field=models.IntegerField(default=100, verbose_name='商品库存'),
        ),
    ]
